services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: biblioteca
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: UTC
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "443:443"
    volumes:
      - ./src/main/resources/ssl:/ssl
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/biblioteca?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 443
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY_STORE: /ssl/cert.p12
      SERVER_SSL_KEY_STORE_PASSWORD: alexandria
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
      LANG: es_ES.UTF-8
      LANGUAGE: es_ES:es
      LC_ALL: es_ES.UTF-8
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
volumes:
  mysql_data:
